### ISSUE TITLE
time subscriptions

### ISSUE THREAD

**Issue by smudge202** [smudge202/clean-living#6]
- We need the concept of time within the game
- Components of our engine will be able to subscribe to be notified when a certain game time happens
- Components of our engine will be able to subscribe to be notified at regular game time intervals
- As a System I want to know what the current game time is

**Comment by herecydev** [comment]
Could post something similar to the following to give us a little background on the issue:

A subscriber can request that it is invoked every unit of time. By allowing components to subscribe, each component is highly modular, allowing optimization and balance to occur independently of the game engine.

**Comment by smudge202** [comment]
There is also a temporal decoupling (eject the warp core!?) between _game time_ and _real time_.  It is not uncommon for games to have an in-game time running _x_ times faster than real time, though typically these will remain in sync (accounting for the multiplier). What we are proposing currently is that components are only able to subscribe for **game time** and events.

Not going to add scenarios of more info than that or now. @mattridgway and I discussed this yesterday and it became an exciting prospect for the engine. Be keen to hear your first thoughts on this, @herecydev .

**Comment by herecydev** [comment]
There isn't a need for game time to run faster than real time (i.e. from frame to frame). A single frame is the only perceivable difference. i.e @60 FPS you have 16ms to handle thirst/hunger changes and get that rendered (which will be placed onto the GPU buffer and then onto monitor buffer) in preperation for the visual change to be observed. Running faster than that, as far as im aware is unnecessary. Though it does safeguard against FPS increases, which is why I assume they do often run the game time faster.

**Comment by mattridgway** [comment]
I don't think we need to worry about FPS for now - that is a rendering concept and not an engine/decision thing - "services" could register for events at a specific gametime / from a specific gametime / at a particular gametime interval - internally we can have our engines gametime speed be completely responsive to current events - each tick of gametime could be anything 1ms > 1hr real time depending on current load (or any other factor). I've got some thoughts on this I was going to draw up at lunch.

**Comment by herecydev** [comment]
Oh I think I misunderstood what you were discussing! If i understand now, your talking about 24 hours occuring within an hour of realtime. Which is a typical thing to do so that the gamer observers different scenarios (day and night/seasons) etc. Instead of repeating the same sunset over and over.

I think that's a fine approach and subscribing to game time makes sense, as long as you keep that consistent.

**Comment by mattridgway** [comment]
I like the idea of seasons, time of day, etc.

**Comment by herecydev** [comment]
Keep a concept of calendar. Let the weather  engine take care of the rest ;) can have lots of chopped down trees affect climate (no oxygen etc)

**Comment by smudge202** [comment]
Can do any number of things.  The important part is that everything (including the rendering engine) is only able to subscribe to events and game times.  By listening to certain types of events, the rendering engine can detect movement/changes in movement etc, collisions, damage models, etc, which should be sufficient to render everything without any hard dependency on a 16ms (for 60FPS) interval subscription.  It allows the FPS rate to vary, and means nothing has to be ticked constantly.  Only components that need to act upon a change need run, not everything constantly which is where I think a lot of performance hits are taken in traditional game engines.

**Comment by herecydev** [comment]
Yep I love the concept of that, rendering movement is almost relentlessly constant. Weather on the other hand can subscribe sparsely; weather is relatively smooth and is static for longer periods of time

**Comment by herecydev** [comment]
Also by interfacing out stuff you can use a certain dynamic composition to swap things out (ultra, high, medium, low style).

For example, the weather engine can at the most basic level return a fixed pattern of weather, Higher settings could return dynamic weather based on how the actor is acting on the environment (buildings blocking the wind) affecting water flow etc.

**Comment by mattridgway** [comment]
![architecture](https://cloud.githubusercontent.com/assets/2500671/6618748/15cedb2e-c8bd-11e4-8916-dbc99ccc729c.PNG)

TimeController
I can see there would be multiple types of timecontroller that could be injected in, depending on the game/environment/current conditions, something like:
- TestTimeController
  - forward(); - progresses internal time by a single GameTime.Tick
  - forward(GameTime); - progresses internal time by a given gametime
  - subscribe(observer); 
- RealTimeController
  - subscribe(observer);
- DynamicTimeController
  - subscribe(observer);
- FixedTimeController
  - subscribe(observer);

Subscriptions
We decide which elements need to know about each other - such as thirst subscribing to time events and movement events, each of which can be handled inside the thirst controller to decide what the effect of that subscription event would be (eg. 1 min game time = -1 thirst, Ran 1m = -10 thirst) - this can then fire its own events off, perhaps back to the movement controller, which realises you are thirsty so it slows down movement.

Perspective
The game engine keeps track of what you are aware of (eg. the person creeping up behind you, the place you visited 5mins ago), you can either request your entire perspective (me) or subscribe and get perspective updates - which is the way we get updates out of the engine and to the client. This avoids the need to subscribe to each internal controller - perhaps missing one out and gaining an advantage.

**Comment by smudge202** [comment]
Gist from @mattridgway which almost completely removes real time: https://gist.github.com/mattridgway/6ca9241cbf0d8f010a52
